### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by zl9801** [botherder/androidqf#2]
ERROR: Unable to get device state. Please make sure it is connected and authorized. Trying again in 5 seconds...

usb debugging is on

**Comment by botherder** [comment]
Either you have not authorised the host on the device, or you are not using a data cable, or there are other issues with your system. This is not quite enough information to work with.

**Comment by biopsin** [comment]
Im having same issue and adb devices show Im connected and adb shell is working fine
```
List of devices attached
QV710PVB3F             device usb:3-4 product:lineage_pdx203 model:Xperia_1_II device:pdx203 transport_id:7
```
Xperia 1 II - Lineageos-18.1
